#List out prefabs to ignore:
StaminaUpgrade_Greydwarf
StaminaUpgrade_Troll
StaminaUpgrade_Wraith
IronOre
DvergerArbalest_shoot
DvergerArbalest
CapeTest
SledgeCheat
SwordCheat
HealthUpgrade_Bonemass
HealthUpgrade_GDKing
guard_stone_test
Trailership
Player
TorchMist
NPC_HelmetIron_Worn0
NPC_HelmetBronze_Worn0
NPC_ArmorIronChest_Worn
NPC_ArmorIronLegs_Worn
TrainingDummy
VegvisirShard_Bonemass
CapeOdin
HelmetOdin
TankardOdin
ShieldIronSquare
