unique_name: arrow_1
display_name: Whittler
sprite_name: arrow
description: Uncover <color=orange>all</color> projectiles
lore: A true survivalist knows well that range is your greatest ally.
start_message: ''
stop_message: ''
tooltip: ''
defeat_key: ''
achievement_type: Arrows
custom_group_key: ''
custom_pickable_name: ''
goal: 0
duration: 0
reward_type: StatusEffect
achievement_group: ''
achievement_index: 0
item: ''
item_amount: 0
skill: ''
skill_amount: 0
class_experience: 0
start_effects:
- sfx_coins_placed
stop_effects: []
damage_modifiers:
- m_type: Blunt
  m_modifier: Normal
- m_type: Slash
  m_modifier: Normal
- m_type: Pierce
  m_modifier: Normal
- m_type: Chop
  m_modifier: Normal
- m_type: Pickaxe
  m_modifier: Normal
- m_type: Fire
  m_modifier: Normal
- m_type: Frost
  m_modifier: Normal
- m_type: Lightning
  m_modifier: Normal
- m_type: Poison
  m_modifier: Normal
- m_type: Spirit
  m_modifier: Normal
modifiers:
  Attack: 1
  HealthRegen: 1
  StaminaRegen: 1.5
  RaiseSkills: 1
  Speed: 1
  Noise: 1
  MaxCarryWeight: 0
  Stealth: 2
  RunStaminaDrain: 0.5
  DamageReduction: 0
  FallDamage: 1
  EitrRegen: 1
skill_bonus: {}
