unique_name: deer_kill
display_name: Deer Season
sprite_name: TrophyDeer
description: Kill over <color=orange>100</color> Deers
lore: The ancients revered the deer god, Eikthyr, for they knew, with a single blow from it's hard antlers, they would lose all of their will to be.
start_message: ''
stop_message: ''
tooltip: ''
defeat_key: defeated_deer
achievement_type: CustomKills
custom_group_key: ''
custom_pickable_name: ''
goal: 100
duration: 0
reward_type: StatusEffect
achievement_group: ''
achievement_index: 0
item: ''
item_amount: 0
skill: ''
skill_amount: 0
class_experience: 0
start_effects:
- sfx_coins_placed
stop_effects: []
damage_modifiers:
- m_type: Blunt
  m_modifier: Weak
- m_type: Slash
  m_modifier: Normal
- m_type: Pierce
  m_modifier: Weak
- m_type: Chop
  m_modifier: Normal
- m_type: Pickaxe
  m_modifier: Normal
- m_type: Fire
  m_modifier: Normal
- m_type: Frost
  m_modifier: Normal
- m_type: Lightning
  m_modifier: Normal
- m_type: Poison
  m_modifier: Normal
- m_type: Spirit
  m_modifier: Normal
modifiers:
  Attack: 0.95
  HealthRegen: 0.95
  StaminaRegen: 1.05
  RaiseSkills: 1.05
  Speed: 1.05
  Noise: 0.95
  MaxCarryWeight: 0
  Stealth: 1
  RunStaminaDrain: 0.95
  DamageReduction: 0
  FallDamage: 1
  EitrRegen: 1
skill_bonus: {}
