unique_name: greyling_kill
display_name: Greyling Massacre
sprite_name: Resin
description: Kill over <color=orange>100</color> Greylings
lore: The mystical forces of the black forest reach beyond it's borders and harass all newcomers with their pesky greylings
start_message: ''
stop_message: ''
tooltip: ''
defeat_key: defeated_greyling
achievement_type: CustomKills
custom_group_key: ''
custom_pickable_name: ''
goal: 100
duration: 0
reward_type: StatusEffect
achievement_group: ''
achievement_index: 0
item: ''
item_amount: 0
skill: ''
skill_amount: 0
class_experience: 0
start_effects:
- sfx_coins_placed
stop_effects: []
damage_modifiers:
- m_type: Blunt
  m_modifier: Normal
- m_type: Slash
  m_modifier: Normal
- m_type: Pierce
  m_modifier: Normal
- m_type: Chop
  m_modifier: Normal
- m_type: Pickaxe
  m_modifier: Normal
- m_type: Fire
  m_modifier: Weak
- m_type: Frost
  m_modifier: Normal
- m_type: Lightning
  m_modifier: Normal
- m_type: Poison
  m_modifier: Normal
- m_type: Spirit
  m_modifier: Normal
modifiers:
  Attack: 1
  HealthRegen: 1.05
  StaminaRegen: 1
  RaiseSkills: 1.05
  Speed: 1
  Noise: 1
  MaxCarryWeight: 50
  Stealth: 1
  RunStaminaDrain: 0.95
  DamageReduction: 0
  FallDamage: 1
  EitrRegen: 1
skill_bonus: {}
