unique_name: staves_1
display_name: Blaster
sprite_name: StaffSkeleton
description: Uncover <color=orange>all</color> staves
lore: The remains of a scarred battlefield left behind by magic leaves deep wounds to the earth itself.
start_message: ''
stop_message: ''
tooltip: ''
defeat_key: ''
achievement_type: Staves
custom_group_key: ''
custom_pickable_name: ''
goal: 0
duration: 0
reward_type: StatusEffect
achievement_group: ''
achievement_index: 0
item: ''
item_amount: 0
skill: ''
skill_amount: 0
class_experience: 0
start_effects:
- fx_DvergerMage_Support_start
stop_effects:
- fx_DvergerMage_Mistile_die
damage_modifiers:
- m_type: Blunt
  m_modifier: Normal
- m_type: Slash
  m_modifier: Normal
- m_type: Pierce
  m_modifier: Normal
- m_type: Chop
  m_modifier: Normal
- m_type: Pickaxe
  m_modifier: Normal
- m_type: Fire
  m_modifier: Normal
- m_type: Frost
  m_modifier: Normal
- m_type: Lightning
  m_modifier: Normal
- m_type: Poison
  m_modifier: Normal
- m_type: Spirit
  m_modifier: Normal
modifiers:
  Attack: 0
  HealthRegen: 1
  StaminaRegen: 1
  RaiseSkills: 1
  Speed: 1
  Noise: 1
  MaxCarryWeight: 0
  Stealth: 1
  RunStaminaDrain: 1
  DamageReduction: 0
  FallDamage: 1
  EitrRegen: 2
skill_bonus: {}
