unique_name: yagluth_1
display_name: The King
sprite_name: TrophyGoblinKing
description: Kill Yagluth over <color=orange>10</color> times
lore: The gates of hell are protected by the dragging corpse that we call Yagluth.
start_message: ''
stop_message: ''
tooltip: ''
defeat_key: defeated_goblinking
achievement_type: CustomKills
custom_group_key: ''
custom_pickable_name: ''
goal: 10
duration: 0
reward_type: StatusEffect
achievement_group: ''
achievement_index: 0
item: ''
item_amount: 0
skill: ''
skill_amount: 0
class_experience: 0
start_effects:
- sfx_coins_placed
stop_effects: []
damage_modifiers:
- m_type: Blunt
  m_modifier: Normal
- m_type: Slash
  m_modifier: Normal
- m_type: Pierce
  m_modifier: Normal
- m_type: Chop
  m_modifier: Normal
- m_type: Pickaxe
  m_modifier: Normal
- m_type: Fire
  m_modifier: Resistant
- m_type: Frost
  m_modifier: Normal
- m_type: Lightning
  m_modifier: Normal
- m_type: Poison
  m_modifier: Normal
- m_type: Spirit
  m_modifier: Normal
modifiers:
  Attack: 1
  HealthRegen: 1.15
  StaminaRegen: 1
  RaiseSkills: 1.15
  Speed: 1
  Noise: 1
  MaxCarryWeight: 0
  Stealth: 1
  RunStaminaDrain: 1
  DamageReduction: 0
  FallDamage: 1
  EitrRegen: 1.1
skill_bonus: {}
