name: CalmingGloves
clonePrefabName: 
craftingStation: $piece_workbench
minStationLevel: 2
maxStationLevelCap: 
repairStation: 
amount: 1
disabled: false
disabledUpgrade: false
requireOnlyOneIngredient: false
upgrade_reqs: []
reqs:
- LeatherScraps:20:5:False
- AT_HasTamed_Item:4:4:False
- TrollHide:10:5:False
- DeerHide:20:5:False
- BlackBearPelt_TW:10:5:False

