creature_prefab_name: Blob
bounty_name: Blob the Slime
sprite_name: TrophyBlob
biome: Swamp
reward_type: Item
item_reward:
  item_name: FineWood
  amount: 30
skill_reward:
  type: None
  amount: 0
experience_reward: 0
bounty_health: 50
damage_multiplier: 1
damages:
  blunt: 10
  slash: 0
  pierce: 0
  fire: 0
  frost: 0
  lightning: 0
  poison: 5
  spirit: 0
level: 1
defeat_key: defeated_blob
cost: 0
currency: Coins
