creature_prefab_name: BlobElite
bounty_name: Blob the Corrupted
sprite_name: skull
biome: Swamp
reward_type: Item
item_reward:
  item_name: Coins
  amount: 150
skill_reward:
  type: None
  amount: 0
experience_reward: 0
bounty_health: 150
damage_multiplier: 1.3
damages:
  blunt: 20
  slash: 0
  pierce: 0
  fire: 0
  frost: 0
  lightning: 0
  poison: 10
  spirit: 0
level: 3
defeat_key: defeated_blobelite
cost: 0
currency: Coins
