creature_prefab_name: Boar
bounty_name: Boar the Wretched
sprite_name: TrophyBoar
biome: Meadows
reward_type: Item
item_reward:
  item_name: Coins
  amount: 50
skill_reward:
  type: None
  amount: 0
experience_reward: 0
bounty_health: 500
damage_multiplier: 2
damages:
  blunt: 10
  slash: 0
  pierce: 0
  fire: 5
  frost: 0
  lightning: 0
  poison: 0
  spirit: 0
level: 3
defeat_key: defeated_boar
cost: 0
currency: Coins
