creature_prefab_name: Bonemass
bounty_name: Bonemass the Decaying
sprite_name: TrophyBonemass
biome: BlackForest
reward_type: Skill
item_reward:
  item_name: ''
  amount: 0
skill_reward:
  type: Clubs
  amount: 20000
experience_reward: 0
bounty_health: 5000
damage_multiplier: 2
damages:
  blunt: 60
  slash: 0
  pierce: 0
  fire: 0
  frost: 0
  lightning: 0
  poison: 30
  spirit: 0
level: 3
defeat_key: defeated_bonemass
cost: 0
currency: Coins
