creature_prefab_name: Dragon
bounty_name: Dragon the Mighty
sprite_name: TrophyDragonQueen
biome: Mountain
reward_type: Skill
item_reward:
  item_name: ''
  amount: 0
skill_reward:
  type: Axes
  amount: 25000
experience_reward: 0
bounty_health: 7500
damage_multiplier: 2.5
damages:
  blunt: 0
  slash: 80
  pierce: 0
  fire: 50
  frost: 0
  lightning: 0
  poison: 0
  spirit: 0
level: 3
defeat_key: defeated_dragon
cost: 0
currency: Coins
