creature_prefab_name: Draugr
bounty_name: Draugr the Undead
sprite_name: TrophyDraugr
biome: BlackForest
reward_type: Item
item_reward:
  item_name: IronScrap
  amount: 10
skill_reward:
  type: None
  amount: 0
experience_reward: 0
bounty_health: 100
damage_multiplier: 1.2
damages:
  blunt: 0
  slash: 15
  pierce: 0
  fire: 0
  frost: 5
  lightning: 0
  poison: 0
  spirit: 0
level: 2
defeat_key: defeated_draugr
cost: 0
currency: Coins
