creature_prefab_name: Draugr_Ranged
bounty_name: Draugr the Archer
sprite_name: TrophyDraugrFem
biome: BlackForest
reward_type: Item
item_reward:
  item_name: BronzeScrap
  amount: 20
skill_reward:
  type: None
  amount: 0
experience_reward: 0
bounty_health: 100
damage_multiplier: 1.1
damages:
  blunt: 0
  slash: 0
  pierce: 15
  fire: 0
  frost: 5
  lightning: 0
  poison: 0
  spirit: 0
level: 2
defeat_key: defeated_draugr_ranged
cost: 0
currency: Coins
