creature_prefab_name: Draugr_Elite
bounty_name: Draugr the Warden
sprite_name: TrophyDraugrElite
biome: BlackForest
reward_type: Item
item_reward:
  item_name: CopperScrap
  amount: 15
skill_reward:
  type: None
  amount: 0
experience_reward: 0
bounty_health: 200
damage_multiplier: 1.5
damages:
  blunt: 0
  slash: 20
  pierce: 10
  fire: 0
  frost: 0
  lightning: 0
  poison: 0
  spirit: 0
level: 3
defeat_key: defeated_draugr_elite
cost: 0
currency: Coins
