creature_prefab_name: Fenring_Cultist
bounty_name: Fenring the Devoted
sprite_name: TrophyCultist
biome: Plains
reward_type: Skill
item_reward:
  item_name: ''
  amount: 0
skill_reward:
  type: Blocking
  amount: 8000
experience_reward: 0
bounty_health: 200
damage_multiplier: 1.2
damages:
  blunt: 0
  slash: 15
  pierce: 5
  fire: 0
  frost: 0
  lightning: 0
  poison: 0
  spirit: 0
level: 2
defeat_key: defeated_fenring_cultist
cost: 0
currency: Coins
