creature_prefab_name: Goblin
bounty_name: Goblin the Menace
sprite_name: TrophyGoblin
biome: BlackForest
reward_type: Skill
item_reward:
  item_name: ''
  amount: 0
skill_reward:
  type: Spears
  amount: 5000
experience_reward: 0
bounty_health: 175
damage_multiplier: 1.2
damages:
  blunt: 0
  slash: 20
  pierce: 10
  fire: 0
  frost: 0
  lightning: 0
  poison: 0
  spirit: 0
level: 2
defeat_key: defeated_goblin
cost: 0
currency: Coins
