creature_prefab_name: GoblinBrute
bounty_name: Goblin the Bulwark
sprite_name: TrophyGoblinBrute
biome: BlackForest
reward_type: Skill
item_reward:
  item_name: ''
  amount: 0
skill_reward:
  type: Blocking
  amount: 10000
experience_reward: 0
bounty_health: 800
damage_multiplier: 1.5
damages:
  blunt: 30
  slash: 0
  pierce: 20
  fire: 0
  frost: 0
  lightning: 0
  poison: 0
  spirit: 0
level: 3
defeat_key: defeated_goblinbrute
cost: 0
currency: Coins
