name: ShieldBoneTower
m_weight: 4
m_name: $item_shield_bonetower
m_description: $item_shield_bonetower_description
clonePrefabName: 
mockName: 
customIcon: 
material: 
materials: 
customVisual: 
snapshotRotation: 
snapshotOnMaterialChange: true
sizeMultiplier: 1
scale_weight_by_quality: 0
Primary_Attack: 
Secondary_Attack: 
Damage: 
Damage_Per_Level: 
Armor:
  armor: 100
  armorPerLevel: 1
FoodStats: 
Moddifiers:
  m_movementModifier: -0.25
  m_EitrRegen: 0
  m_homeItemsStaminaModifier: 0
  m_heatResistanceModifier: 0
  m_jumpStaminaModifier: -0.1
  m_attackStaminaModifier: 0
  m_blockStaminaModifier: 0
  m_dodgeStaminaModifier: 0
  m_swimStaminaModifier: 0
  m_sneakStaminaModifier: 0
  m_runStaminaModifier: -0.1
SE_Equip: 
SE_SET_Equip: 
ShieldStats:
  m_blockPower: 38
  m_blockPowerPerLevel: 11
  m_timedBlockBonus: 0
  m_deflectionForce: 100
  m_deflectionForcePerLevel: 5
m_maxStackSize: 1
m_canBeReparied: true
m_destroyBroken: false
m_dodgeable: true
Attack_status_effect: 
Attack_status_effect_chance: 1
spawn_on_hit: 
spawn_on_terrain_hit: 
m_questItem: false
m_teleportable: true
m_backstabbonus: 4
m_knockback: 40
m_useDurability: true
m_useDurabilityDrain: 1
m_durabilityDrain: 0
m_maxDurability: 200
m_durabilityPerLevel: 50
m_equipDuration: 0.2
Attach_Override: None
m_skillType: Blocking
m_animationState: Shield
m_itemType: Shield
m_toolTier: 1
m_maxQuality: 3
m_value: 0
ConsumableStatusEffect: 
damageModifiers: 
- Pierce:Resistant
GEffects: 
GEffectsPLUS:
  Hit_Effects:
  - name: vfx_clubhit
    m_enabled: true
    m_variant: -1
    m_attach: false
    m_follow: false
    m_inheritParentRotation: false
    m_inheritParentScale: false
    m_multiplyParentVisualScale: false
    m_randomRotation: false
    m_scale: false
    m_childTransform: ''
  - name: sfx_club_hit
    m_enabled: true
    m_variant: -1
    m_attach: false
    m_follow: false
    m_inheritParentRotation: false
    m_inheritParentScale: false
    m_multiplyParentVisualScale: false
    m_randomRotation: false
    m_scale: false
    m_childTransform: ''
  Hit_Terrain_Effects: []
  Start_Effect: []
  Hold_Start_Effects: []
  Trigger_Effect: []
  Trail_Effect: []
