Abomination: Boss
Troll: Boss
StoneGolem: Boss
Lox: Boss
Skeleton_Poison: Boss
BlobTar: Boss
Hatchling: Boss
GoblinBrute: Boss
Serpent: Boss
# Monstrum:
ObsidianGolem_TW: Boss
# Wizardry:
GreydwarfMage_TW: Boss
SkeletonMage_TW: Boss
FenringMage_TW: Boss
GoblinMage_TW: Boss
CorruptedDvergerMage_TW: Boss
SummonedSeeker_TW: Boss

#Factions:
#Players
#AnimalsVeg
#ForestMonsters
#Undead
#Demon
#MountainMonsters
#SeaMonsters
#PlainsMonsters
#Boss
#MistlandsMonsters
#Dverger