MountainsCreatures1:
  - Ulv
  - Wolf
  - Wolf
  - Ulv
  - Wolf
  - Wolf
MountainsCreatures2:
  - Fenring_Cultist
  - Wolf
  - Wolf
  - Fenring_Cultist
  - Wolf
  - Wolf
MountainsCreatures3:
  - Ulv
  - Wolf
  - Fenring_Cultist
  - Ulv
  - Wolf
  - Fenring_Cultist
