name: Ashlands Treasure
sprite_name: map
currency: Coins
cost: 150
biome: AshLands
loot:
- item_name: Coins
  min_stack: 100
  max_stack: 200
  weight: 1
- item_name: FlametalOre
  min_stack: 2
  max_stack: 10
  weight: 1
- item_name: IronScrap
  min_stack: 1
  max_stack: 30
  weight: 1
- item_name: BugMeat
  min_stack: 1
  max_stack: 20
  weight: 1
