name: Deep North Treasure
sprite_name: map
currency: Coins
cost: 150
biome: DeepNorth
loot:
- item_name: Coins
  min_stack: 100
  max_stack: 200
  weight: 1
- item_name: Softtissue
  min_stack: 2
  max_stack: 10
  weight: 1
- item_name: SilverOre
  min_stack: 1
  max_stack: 30
  weight: 1
- item_name: MushroomMagecap
  min_stack: 1
  max_stack: 20
  weight: 1
