name: Plains Treasure
sprite_name: map
currency: Coins
cost: 50
biome: Plains
loot:
- item_name: Coins
  min_stack: 100
  max_stack: 200
  weight: 1
- item_name: BlackMetalScrap
  min_stack: 2
  max_stack: 10
  weight: 1
- item_name: Barley
  min_stack: 1
  max_stack: 20
  weight: 1
- item_name: Flax
  min_stack: 1
  max_stack: 20
  weight: 1
