name: Swamp Treasure
sprite_name: map
currency: Coins
cost: 30
biome: Swamp
loot:
- item_name: Coins
  min_stack: 10
  max_stack: 20
  weight: 1
- item_name: IronScrap
  min_stack: 2
  max_stack: 10
  weight: 1
- item_name: Bloodbag
  min_stack: 1
  max_stack: 20
  weight: 1
- item_name: Thistle
  min_stack: 1
  max_stack: 50
  weight: 1
